defaults:
  - _self_
  - experiment_data_paths: predict_default

parameters:
  file_type: "*.tif"
  n_tiles: [1, 4, 4]
  tile_overlap: 0.125
  batch_size: 4
  min_size: 10            # remove_small_objects floor for CC instance labels
